# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d73ce3a561b2b0a36cdd9beb041e8832"
name = "sticky-add-to-cart"
handle = "sticky-add-to-cart-41"
application_url = "https://loan-supports-belief-advertisements.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://loan-supports-belief-advertisements.trycloudflare.com/auth/callback", "https://loan-supports-belief-advertisements.trycloudflare.com/auth/shopify/callback", "https://loan-supports-belief-advertisements.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
